### ISSUE TITLE
Parsing error when variable name starts with pronoun keyword

### ISSUE THREAD

**Issue by wizered67** [cwfitzgerald/rockstar-webpiler#6]
I believe variable names that start with a pronoun keyword (he, she, etc) aren't being parsed correctly. For example, `Henry is cool` gives an error (https://rockstar.connorwfitzgerald.com/enFm-bwE2Zk), but `Bob is cool` works fine (https://rockstar.connorwfitzgerald.com/cPLQO-lAFBk). I believe this is related to pronouns since `Shelley is cool` also gives an error.

**Comment by cwfitzgerald** [comment]
Yup! Thank you for the bug report. The second I saw this I knew exactly what caused it. My parser deals with pronouns in a case insensitive way and then allows you to NOT put a space after the pronoun. Adding those together there's this bug. I'll fix it shortly.

**Comment by cwfitzgerald** [comment]
Alright, changes should also be live. Make sure you reload with a clear cache. (Shift-F5) to get the new JS file.
